function [response] = Get_Response_2D(eye,buffered_signal,eye_pos, params)
% Generates the response of the eye as it views a signal from a specified
% location. 
%
% Syntax: 
%    [response] = Get_Response(eye,bufferedSignal,eyePos, params)
%
% Description: 
%     This function takes in a model of the eye, a buffered signal, the
%     eye's current position, and params. It generates a vector of the 
%     receptor's response to looking at the signal from the given position.
%     This differs from Get_Response in that this function is used for 2D
%     inputs.
%
% Inputs:
%     eye            - A vector with 1's where there are receptors
%     bufferedSignal - A vector which contains the signal padded by 0s
%     eyePos         - The current position of the eye  
%     params         - Standard parameters structure for the calculation.
%                      See EyeMovements_1d for details 
%
% Outputs:
%     response       - A 1D vector with size equal to the number of
%                       receptors. Each value is the corresponding
%                       receptors response to the stimuli from its
%                       position. e.g. index 10 contains the output
%                       generated by receptor 10 in the eye as it looks at
%                       the signal
%
% Optional key/value pairs:
%     None.
%
% See also: 
%
% History:
%   03/22/18  ak   First draft

%% Calculate starting position relative to the vector index
adjustedPos(1) = params.maxEyeMovement + eye_pos(1);
adjustedPos(2) = params.maxEyeMovement + eye_pos(2);
receptorIndex = find(eye == 1);
receptorIndex = receptorIndex(:);
pos_0 = floor(params.nSignal/2) - floor(params.eyeSize/2);

%% Find responses and record them in response vector

possibleVisualField = buffered_signal(adjustedPos(1):adjustedPos(1) + params.nSignal-1,...
                adjustedPos(2):adjustedPos(2) + params.nSignal-1);
actualVisualField = possibleVisualField(pos_0:pos_0+params.eyeSize-1,pos_0:pos_0+params.eyeSize-1);
response = actualVisualField .* eye;
response = response(:);
response = response(receptorIndex);
end

